version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install -g serve
      - npm install --prefix backend
      - npm install --prefix backend
      - npm install

artifacts:
  files:
    - '**/*'