# main command: npm run start --prefix frontend
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install -g serve
      - npm install --prefix backend
      - npm install --prefix frontend
      - npm run build --prefix frontend
      - pwd
      - ls -l

artifacts:
  files:
    - 'backend/build/**/*'
    - 'frontend/build/**/*'
