# main command: npm run start --prefix backend
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install --prefix backend
      - npm install --prefix frontend
      - npm run build --prefix backend

artifacts:
  files:
    - 'backend/build/**/*'
    - 'frontend/build/**/*'
