version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install -g serve
      - npm install

artifacts:
  files:
    - 'backend/build/**/*'
    - 'frontend/build/**/*'
    - 'package.json'